//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_TextureFormatWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(UnityEngine.TextureFormat));
		L.RegVar("Alpha8", get_Alpha8, null);
		L.RegVar("ARGB4444", get_ARGB4444, null);
		L.RegVar("RGB24", get_RGB24, null);
		L.RegVar("RGBA32", get_RGBA32, null);
		L.RegVar("ARGB32", get_ARGB32, null);
		L.RegVar("RGB565", get_RGB565, null);
		L.RegVar("R16", get_R16, null);
		L.RegVar("DXT1", get_DXT1, null);
		L.RegVar("DXT5", get_DXT5, null);
		L.RegVar("RGBA4444", get_RGBA4444, null);
		L.RegVar("BGRA32", get_BGRA32, null);
		L.RegVar("RHalf", get_RHalf, null);
		L.RegVar("RGHalf", get_RGHalf, null);
		L.RegVar("RGBAHalf", get_RGBAHalf, null);
		L.RegVar("RFloat", get_RFloat, null);
		L.RegVar("RGFloat", get_RGFloat, null);
		L.RegVar("RGBAFloat", get_RGBAFloat, null);
		L.RegVar("YUY2", get_YUY2, null);
		L.RegVar("BC4", get_BC4, null);
		L.RegVar("BC5", get_BC5, null);
		L.RegVar("BC6H", get_BC6H, null);
		L.RegVar("BC7", get_BC7, null);
		L.RegVar("DXT1Crunched", get_DXT1Crunched, null);
		L.RegVar("DXT5Crunched", get_DXT5Crunched, null);
		L.RegVar("PVRTC_RGB2", get_PVRTC_RGB2, null);
		L.RegVar("PVRTC_RGBA2", get_PVRTC_RGBA2, null);
		L.RegVar("PVRTC_RGB4", get_PVRTC_RGB4, null);
		L.RegVar("PVRTC_RGBA4", get_PVRTC_RGBA4, null);
		L.RegVar("ETC_RGB4", get_ETC_RGB4, null);
		L.RegVar("ATC_RGB4", get_ATC_RGB4, null);
		L.RegVar("ATC_RGBA8", get_ATC_RGBA8, null);
		L.RegVar("EAC_R", get_EAC_R, null);
		L.RegVar("EAC_R_SIGNED", get_EAC_R_SIGNED, null);
		L.RegVar("EAC_RG", get_EAC_RG, null);
		L.RegVar("EAC_RG_SIGNED", get_EAC_RG_SIGNED, null);
		L.RegVar("ETC2_RGB", get_ETC2_RGB, null);
		L.RegVar("ETC2_RGBA1", get_ETC2_RGBA1, null);
		L.RegVar("ETC2_RGBA8", get_ETC2_RGBA8, null);
		L.RegVar("ASTC_RGB_4x4", get_ASTC_RGB_4x4, null);
		L.RegVar("ASTC_RGB_5x5", get_ASTC_RGB_5x5, null);
		L.RegVar("ASTC_RGB_6x6", get_ASTC_RGB_6x6, null);
		L.RegVar("ASTC_RGB_8x8", get_ASTC_RGB_8x8, null);
		L.RegVar("ASTC_RGB_10x10", get_ASTC_RGB_10x10, null);
		L.RegVar("ASTC_RGB_12x12", get_ASTC_RGB_12x12, null);
		L.RegVar("ASTC_RGBA_4x4", get_ASTC_RGBA_4x4, null);
		L.RegVar("ASTC_RGBA_5x5", get_ASTC_RGBA_5x5, null);
		L.RegVar("ASTC_RGBA_6x6", get_ASTC_RGBA_6x6, null);
		L.RegVar("ASTC_RGBA_8x8", get_ASTC_RGBA_8x8, null);
		L.RegVar("ASTC_RGBA_10x10", get_ASTC_RGBA_10x10, null);
		L.RegVar("ASTC_RGBA_12x12", get_ASTC_RGBA_12x12, null);
		L.RegVar("ETC_RGB4_3DS", get_ETC_RGB4_3DS, null);
		L.RegVar("ETC_RGBA8_3DS", get_ETC_RGBA8_3DS, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Alpha8(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.TextureFormat.Alpha8);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ARGB4444(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.TextureFormat.ARGB4444);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_RGB24(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.TextureFormat.RGB24);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_RGBA32(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.TextureFormat.RGBA32);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ARGB32(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.TextureFormat.ARGB32);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_RGB565(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.TextureFormat.RGB565);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_R16(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.TextureFormat.R16);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_DXT1(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.TextureFormat.DXT1);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_DXT5(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.TextureFormat.DXT5);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_RGBA4444(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.TextureFormat.RGBA4444);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_BGRA32(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.TextureFormat.BGRA32);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_RHalf(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.TextureFormat.RHalf);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_RGHalf(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.TextureFormat.RGHalf);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_RGBAHalf(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.TextureFormat.RGBAHalf);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_RFloat(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.TextureFormat.RFloat);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_RGFloat(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.TextureFormat.RGFloat);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_RGBAFloat(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.TextureFormat.RGBAFloat);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_YUY2(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.TextureFormat.YUY2);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_BC4(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.TextureFormat.BC4);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_BC5(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.TextureFormat.BC5);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_BC6H(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.TextureFormat.BC6H);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_BC7(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.TextureFormat.BC7);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_DXT1Crunched(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.TextureFormat.DXT1Crunched);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_DXT5Crunched(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.TextureFormat.DXT5Crunched);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_PVRTC_RGB2(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.TextureFormat.PVRTC_RGB2);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_PVRTC_RGBA2(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.TextureFormat.PVRTC_RGBA2);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_PVRTC_RGB4(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.TextureFormat.PVRTC_RGB4);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_PVRTC_RGBA4(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.TextureFormat.PVRTC_RGBA4);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ETC_RGB4(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.TextureFormat.ETC_RGB4);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ATC_RGB4(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.TextureFormat.ATC_RGB4);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ATC_RGBA8(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.TextureFormat.ATC_RGBA8);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_EAC_R(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.TextureFormat.EAC_R);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_EAC_R_SIGNED(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.TextureFormat.EAC_R_SIGNED);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_EAC_RG(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.TextureFormat.EAC_RG);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_EAC_RG_SIGNED(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.TextureFormat.EAC_RG_SIGNED);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ETC2_RGB(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.TextureFormat.ETC2_RGB);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ETC2_RGBA1(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.TextureFormat.ETC2_RGBA1);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ETC2_RGBA8(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.TextureFormat.ETC2_RGBA8);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ASTC_RGB_4x4(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.TextureFormat.ASTC_RGB_4x4);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ASTC_RGB_5x5(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.TextureFormat.ASTC_RGB_5x5);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ASTC_RGB_6x6(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.TextureFormat.ASTC_RGB_6x6);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ASTC_RGB_8x8(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.TextureFormat.ASTC_RGB_8x8);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ASTC_RGB_10x10(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.TextureFormat.ASTC_RGB_10x10);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ASTC_RGB_12x12(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.TextureFormat.ASTC_RGB_12x12);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ASTC_RGBA_4x4(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.TextureFormat.ASTC_RGBA_4x4);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ASTC_RGBA_5x5(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.TextureFormat.ASTC_RGBA_5x5);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ASTC_RGBA_6x6(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.TextureFormat.ASTC_RGBA_6x6);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ASTC_RGBA_8x8(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.TextureFormat.ASTC_RGBA_8x8);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ASTC_RGBA_10x10(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.TextureFormat.ASTC_RGBA_10x10);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ASTC_RGBA_12x12(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.TextureFormat.ASTC_RGBA_12x12);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ETC_RGB4_3DS(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.TextureFormat.ETC_RGB4_3DS);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ETC_RGBA8_3DS(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.TextureFormat.ETC_RGBA8_3DS);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		UnityEngine.TextureFormat o = (UnityEngine.TextureFormat)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

