-- Index                            int                              序号
-- skillID                          int                              技能ID
-- skillName                        string                           技能名称
-- skillDescription                 string                           描述
-- skillIcon                        string                           技能图标
-- skillLevel                       int                              等级
-- UpdateCost                       string                           技能升级消耗
-- normalAttck                      int                              是否普通攻击
-- SkillAttckType                   int                              技能攻击类型
-- skillType                        int                              技能分类
-- priority                         int                              施放优先级
-- cdTime                           int                              冷却时间
-- initialCDTime                    float                            触发几率
-- moveType                         int                              位移类型
-- moveDistance                     int                              位移距离
-- animation_Move                   int                              位移动作
-- animation_AfterMove              int                              位移后施法动作
-- moveSpeed                        int                              位移速度
-- targetType                       int                              影响目标类型
-- targetChooseType                 string                           目标选择方式
-- targetChooseConitionValue        int                              目标选择条件数值
-- targetEffectType                 int                              影响范围类型
-- targetEffectArea                 int                              影响范围
-- hasBullet                        int                              是否有子弹
-- bulletId                         int                              技能子弹ID
-- effectTarget                     int                              技能效果目标
-- effecttype                       int                              技能效果类型
-- effectValue                      int                              技能效果数值
-- relativeAttributeID              int                              技能效果相关属性类型
-- relativeAttributeFactor          int                              技能效果相关属性系数
-- effectAttributeSource            int                              技能效果相关属性来源
-- delay                            float                            延迟时间
-- effectPrefab                     int                              技能效果特效
-- effectFloatText                  int                              技能效果提示

return {
	[1] = {
		skillID = 1,
		skillName = "近战",
		skillDescription = "刀砍",
		skillIcon = "chuizi.png",
		skillLevel = 1,
		UpdateCost = "gold,1066",
		normalAttck = 1,
		SkillAttckType = 0,
		skillType = 0,
		priority = 1,
		cdTime = 1,
		initialCDTime = 1,
		moveType = 0,
		moveDistance = 0,
		animation_Move = 0,
		animation_AfterMove = 0,
		moveSpeed = 0,
		targetType = 0,
		targetChooseType = "0",
		targetChooseConitionValue = 1,
		targetEffectType = 0,
		targetEffectArea = 0,
		hasBullet = 0,
		bulletId = 0,
		effectTarget = 0,
		effecttype = 0,
		effectValue = 10,
		relativeAttributeID = 0,
		relativeAttributeFactor = 1,
		effectAttributeSource = 0,
		delay = 0.5,
		effectPrefab = 1,
		effectFloatText = 10,
	},
	[2] = {
		skillID = 2,
		skillName = "远程",
		skillDescription = "暴风雪",
		skillIcon = "chuizi.png",
		skillLevel = 1,
		UpdateCost = "gold,1066",
		normalAttck = 1,
		SkillAttckType = 1,
		skillType = 0,
		priority = 2,
		cdTime = 1,
		initialCDTime = 1,
		moveType = 0,
		moveDistance = 0,
		animation_Move = 0,
		animation_AfterMove = 0,
		moveSpeed = 0,
		targetType = 0,
		targetChooseType = "0",
		targetChooseConitionValue = 1,
		targetEffectType = 0,
		targetEffectArea = 0,
		hasBullet = 0,
		bulletId = 0,
		effectTarget = 0,
		effecttype = 0,
		effectValue = 10,
		relativeAttributeID = 0,
		relativeAttributeFactor = 1,
		effectAttributeSource = 0,
		delay = 1,
		effectPrefab = 1,
		effectFloatText = 10,
	},
	[3] = {
		skillID = 3,
		skillName = "远程",
		skillDescription = "弓箭",
		skillIcon = "chuizi.png",
		skillLevel = 1,
		UpdateCost = "gold,1066",
		normalAttck = 1,
		SkillAttckType = 1,
		skillType = 0,
		priority = 1,
		cdTime = 1,
		initialCDTime = 1,
		moveType = 0,
		moveDistance = 0,
		animation_Move = 0,
		animation_AfterMove = 0,
		moveSpeed = 0,
		targetType = 0,
		targetChooseType = "0",
		targetChooseConitionValue = 1,
		targetEffectType = 0,
		targetEffectArea = 0,
		hasBullet = 1,
		bulletId = 1,
		effectTarget = 0,
		effecttype = 0,
		effectValue = 10,
		relativeAttributeID = 0,
		relativeAttributeFactor = 1,
		effectAttributeSource = 0,
		delay = 1,
		effectPrefab = 1,
		effectFloatText = 10,
	},
	[4] = {
		skillID = 4,
		skillName = "远程",
		skillDescription = "寒冰箭",
		skillIcon = "chuizi.png",
		skillLevel = 1,
		UpdateCost = "gold,1066",
		normalAttck = 1,
		SkillAttckType = 1,
		skillType = 0,
		priority = 2,
		cdTime = 1,
		initialCDTime = 1,
		moveType = 0,
		moveDistance = 0,
		animation_Move = 0,
		animation_AfterMove = 0,
		moveSpeed = 0,
		targetType = 0,
		targetChooseType = "0",
		targetChooseConitionValue = 1,
		targetEffectType = 0,
		targetEffectArea = 0,
		hasBullet = 1,
		bulletId = 2,
		effectTarget = 0,
		effecttype = 0,
		effectValue = 10,
		relativeAttributeID = 0,
		relativeAttributeFactor = 1,
		effectAttributeSource = 0,
		delay = 1,
		effectPrefab = 1,
		effectFloatText = 10,
	},
	[5] = {
		skillID = 5,
		skillName = "远程",
		skillDescription = "火球",
		skillIcon = "chuizi.png",
		skillLevel = 1,
		UpdateCost = "gold,1066",
		normalAttck = 1,
		SkillAttckType = 1,
		skillType = 0,
		priority = 1,
		cdTime = 1,
		initialCDTime = 1,
		moveType = 0,
		moveDistance = 0,
		animation_Move = 0,
		animation_AfterMove = 0,
		moveSpeed = 0,
		targetType = 0,
		targetChooseType = "0",
		targetChooseConitionValue = 1,
		targetEffectType = 0,
		targetEffectArea = 0,
		hasBullet = 1,
		bulletId = 0,
		effectTarget = 0,
		effecttype = 0,
		effectValue = 10,
		relativeAttributeID = 0,
		relativeAttributeFactor = 1,
		effectAttributeSource = 0,
		delay = 1,
		effectPrefab = 1,
		effectFloatText = 10,
	},
	[6] = {
		skillID = 6,
		skillName = "远程",
		skillDescription = "回血",
		skillIcon = "chuizi.png",
		skillLevel = 1,
		UpdateCost = "gold,1066",
		normalAttck = 1,
		SkillAttckType = 1,
		skillType = 1,
		priority = 2,
		cdTime = 1,
		initialCDTime = 1,
		moveType = 0,
		moveDistance = 0,
		animation_Move = 0,
		animation_AfterMove = 0,
		moveSpeed = 0,
		targetType = 1,
		targetChooseType = "4",
		targetChooseConitionValue = 5,
		targetEffectType = 1,
		targetEffectArea = 5,
		hasBullet = 1,
		bulletId = 0,
		effectTarget = 2,
		effecttype = 1,
		effectValue = 10,
		relativeAttributeID = 0,
		relativeAttributeFactor = 1,
		effectAttributeSource = 0,
		delay = 1,
		effectPrefab = 1,
		effectFloatText = 10,
	},
}
